# DVA

In [1]:
import numpy as np

In [2]:
x1 = [1,2,3,4]
x2 = [5,6,7,8]

In [3]:
x1 + x2

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
n1 = np.array(x1)
n2 = np.array(x2) 
print(n1,n2)

[1 2 3 4] [5 6 7 8]

In [5]:
n1 + n2

array([ 6,  8, 10, 12])

In [6]:
n1 - n2

array([-4, -4, -4, -4])

In [7]:
x1 = [1,2,3,4,5,6]
x2 = [7,8]

In [8]:
n1 = np.array(x1)
n2 = np.array(x2)

numpy has limitation that it will work for only homogenous system

discovery of pandas was done to break limitation of numpy

In [2]:
import pandas as pd

In [10]:
p1 = pd.Series(x1)
p2 = pd.Series(x2)
p1 + p2

0     8.0
1    10.0
2     NaN
3     NaN
4     NaN
5     NaN
dtype: float64

In [11]:
import pandas as pd
dataset = pd.read_csv(r'C:\Users\Shraddha Maurya\OneDrive\Pictures\python replc\Banking Problem Statement (1).csv') # r is used for c drive

In [12]:
dataset.head(10) # shows top 5 rows

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [13]:
dataset.tail(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [14]:
dataset.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [15]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [16]:
dataset.isnull()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
dataset.isnull().sum() # helps to find null value in columns

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [19]:
dataset['High_balance'] = dataset['Balance']>100000
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,High_balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,False
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,False
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,True
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,False
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,True

In [20]:
dataset.drop('RowNumber', axis=1, inplace=True) #axis = 1 means changes in columns and axis = 0 for row

In [21]:
dataset.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,High_balance
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,False
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,False
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,True
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,False
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,True

In [22]:
dataset.drop(columns = ['CustomerId','Surname'], inplace=True)

In [30]:
x = dataset.iloc[:,:-2]
x.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [31]:
y = dataset.iloc[:,-2:-1]
y.head()

   Exited
0       1
1       0
2       1
3       0
4       0

to convert it into array add .values

In [32]:
x = dataset.iloc[:,:-2].values 
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

In [3]:
import sklearn

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x['Gender']= le.fit_transform(x['Gender'])
x.head()

Normolisation

In [ ]:
from sklearn.preprocessing import MinMaxScaler 
se = MinMaxScaler()
columns = ['CreditScore', 'Age',	'Tenure',  	'Balance', 	'NumOfProducts', 'EstimatedSalary'] 
x[columns] = se.fit_transform(x[columns])
x.head()

In [ ]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), ['Geography'])], remainder='passthrough') 
x_encoded =ct.fit_transform(x)

In [ ]:
column_name = ct.get_feature_names_out()
x = pd.DataFrame(x_encoded, columns = column_name)
x.head()

In [36]:
dataset = pd.get_dummies(dataset, columns=['Geography'], dtype=int)
dataset.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,High_balance,Geography_France,Geography_Germany,Geography_Spain
0,619,Female,42,2,0.00,1,1,1,101348.88,1,False,1,0,0
1,608,Female,41,1,83807.86,1,0,1,112542.58,0,False,0,0,1
2,502,Female,42,8,159660.80,3,1,0,113931.57,1,True,1,0,0
3,699,Female,39,1,0.00,2,0,0,93826.63,0,False,1,0,0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0,True,0,0,1